### ISSUE TITLE
在react中调用，图片消失时会报错，请问该如何解决？

### ISSUE THREAD

**Issue by iCodeAnt** [TUBB/h5-imageviewer#1]
`
bundle.js:1 Uncaught TypeError: Cannot read property 'childNodes' of undefined
    at pe (bundle.js:1)
    at multipointEndListener (bundle.js:1)
    at HTMLDivElement.multipointEnd (bundle.js:1)
    at HandlerAdmin.dispatch (alloy_finger.js:57)
    at AlloyFinger.end (alloy_finger.js:224)
pe @ bundle.js:1
multipointEndListener @ bundle.js:1
multipointEnd @ bundle.js:1
HandlerAdmin.dispatch @ alloy_finger.js:57
end @ alloy_finger.js:224
Wave.js:31 image list viewer hide
`
在react中调用，图片消失时会报错，请问该如何解决？

**Comment by TUBB** [comment]
你用的是哪个版本，使用0.6.4版本试一下，之前有个老版本出现过这个问题

**Comment by iCodeAnt** [comment]
感谢回复！现在安装的是0.6.4版本的，会报这个错误， 我看git上已经是0.6.5了，但是
https://www.npmjs.com/package/h5-imageviewer
这里是0.6.4版本的，希望可以解决下，万分感谢！！

**Comment by TUBB** [comment]
@iCodeAnt 有可以调试的示例代码吗？我这边本地调试的时候没有出现这个问题哦

**Comment by iCodeAnt** [comment]
太感谢了，现在修改调用方式，也可以不报错了，不知道为什么 我把他放到有些函数里会报错。。
再请问下这个库可以显示图片的页码吗？ 比如底部有几个小圆点表示页码。。

**Comment by iCodeAnt** [comment]
还有个问题，我们用支付宝的 ant mobile 的库，使用了他们的 Modal控件，如果Modal控件弹出来了，图片浏览器的界面就会被挡住，zindex 改很大也没用。。请问有解决方案吗。。

**Comment by iCodeAnt** [comment]
iOS的safari浏览器会挡住，但是安卓的又不会

**Comment by TUBB** [comment]
图片的页码示例程序中有包含，可以参考一下；被Modal覆盖的问题，可以把Modal的zIndex值调小一点。

**Comment by iCodeAnt** [comment]
调整了modal的zIndex 负数都没用。。把Modal的 display 设置成none就可以看到 被挡住的图片浏览器了，这个问题 只会在iOS的 Safari浏览器出现，安卓的浏览器也没有问题

**Comment by TUBB** [comment]
图片库默认z-index是999，Modal默认的z-index是1000。你是在什么时候设置Modal的z-index属性的？

**Comment by iCodeAnt** [comment]
感谢回复！！刚刚查到iOS的Safari浏览器如果css 用到了3d变换会忽略zIndex的设置，
我用iOS设备连接mac 调试了，如果在
pobi_mobile_viewer_container_id 这个图片浏览的div如果style设置了
/* 以毒攻毒 */
    transform: translateZ(100px);
这属性 iOS上Safari就可以正常显示了。。。
https://www.cnblogs.com/qidian10/p/6582247.html
这篇博文里写的
可以帮忙修复下吗。。万分感谢！！

**Comment by iCodeAnt** [comment]
transform: perspective(500px) matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1);
这个3d变换样式在 iOS上Safari会导致zIndex被忽略

**Comment by TUBB** [comment]
@iCodeAnt 你提交一个pr修复一下吧，我这边没有相应的使用场景和测试代码，哈哈。谢谢~

**Comment by iCodeAnt** [comment]
好的，万分感谢~
