### ISSUE TITLE
来回点击图片多次，就会报错：Cannot read property 'childNodes' of undefined

### ISSUE THREAD

**Issue by biology-w** [TUBB/h5-imageviewer#2]
bundle.js:1 Uncaught TypeError: Cannot read property 'childNodes' of undefined
    at we (bundle.js:1)
    at multipointEndListener (bundle.js:1)
    at HTMLDivElement.multipointEnd (bundle.js:1)
    at HandlerAdmin.dispatch (alloy_finger.js:57)
    at AlloyFinger.end (alloy_finger.js:224)

bundle.js:1文件
error:
return G.childNodes[e].childNodes[0]}

**Comment by biology-w** [comment]
在手机内浏览时，图片等直接卡死。所有点击事件无效。
version:
 "h5-imageviewer": "0.6.8",

**Comment by TUBB** [comment]
不好意思，现在才看到问题。在线Demo会出现相同的问题吗？

**Comment by biology-w** [comment]
暂时没有发现。

项目使用的是React Hooks，点击事件直接调用
const onClick = () => {
   const srcs = imageSrcs.map(src => ({ src }));
   showImgListViewer(srcs, { defaultPageIndex: index });
};

**Comment by TUBB** [comment]
麻烦提供一个在线复现bug的demo，多谢~ https://codesandbox.io

**Comment by TUBB** [comment]
我写了一个简单的React Hooks程序，没有复现问题哦~
源码：https://codesandbox.io/s/vigilant-sun-3khwy
DEMO预览：https://3khwy.csb.app/

**Comment by biology-w** [comment]
https://3khwy.csb.app/
多次点击又出现了下面错误：
bundle.js:1 Uncaught TypeError: Cannot read property 'imgList' of null
    at ce (bundle.js:1)
    at r (bundle.js:1)

**Comment by biology-w** [comment]
作者微信可以告知下嘛。
我截图发你

**Comment by TUBB** [comment]
好的，pobitoo
