### ISSUE TITLE
showImgListViewer 的时候，如果defaultPageIndex不是第一张，进入后会有个切换的效果，我希望有个开关

### ISSUE THREAD

**Issue by ndimfed** [TUBB/h5-imageviewer#3]
showImgListViewer 的时候，如果defaultPageIndex不是第一张，进入后会有个切换的效果，我希望有个开关可以把切换的效果关闭，可以让我点开的时候可以直接定位到，现在比较急，有什么可以项目中快速处理的办法吗

**Comment by TUBB** [comment]
刚看到问题，现在还有这个需求嘛，我可以加个开关

**Comment by TUBB** [comment]
可以配置defaultPageIndex
